openapi: 3.0.0
info:
  title: Kiai
  version: '0.1.0'
  contact:
    name: Shadow
    email: shadow@kiaibot.com
    url: 'https://kiaibot.com'
  description: The main API for Kiai
  license:
    name: MIT
    url: 'https://www.mit.edu/~amini/LICENSE.md'
servers:
  - url: 'https://api.kiaibot.com'
paths:
  /status:
    get:
      summary: Get the status of the bot
      responses:
        '200':
          description: Returned when the bot is online
        '408':
          description: Returned when unable to get the bot's status
        '503':
          description: Returned when the bot is offline
      operationId: get-status
      description: Get the status of the bot
components:
  schemas: {}
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: X-API-Key